In [ ]:
# I am doing this in Google Colab

# This is my reminder to connect to the T4 GPU server to run the code a lot faster

# CONNECT TO THE T4 GPU

In [1]:
import numpy as np
import pandas as pd

# Assuming the CSV file is in the same directory as your notebook
df = pd.read_csv('Destiny_Guns.csv')

In [2]:
# Remove the first column
df = df.iloc[:, 1:]

In [3]:
# Convert 'Impact', 'Range', 'RPM', and 'Magazine' columns to numerical data
for column in ['Impact', 'Range', 'RPM', 'Magazine']:
  df[column] = pd.to_numeric(df[column], errors='coerce')

In [4]:
df.head()

Name  Impact  Range     RPM  Magazine  Element  \
0   Ace of Spades    84.0   75.0   140.0      13.0  Kinetic   
1  Ager's Scepter     6.0   69.0  1000.0      97.0   Stasis   
2         Anarchy     NaN    NaN   150.0       6.0      Arc   
3        Arbalest    41.0   36.0     NaN       5.0  Kinetic   
4        Bad Juju    27.0   35.0   450.0      27.0  Kinetic   

                  Type  Rarity  
0          Hand Cannon  Exotic  
1          Trace Rifle  Exotic  
2     Grenade Launcher  Exotic  
3  Linear Fusion Rifle  Exotic  
4          Pulse Rifle  Exotic

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Handle missing values (NaN) - replace with the mean of each column
for column in ['Impact', 'Range', 'RPM', 'Magazine']:
    df[column].fillna(df[column].mean(), inplace=True)

# Define features (X) and target (y)
X = df[['Impact', 'Range', 'RPM', 'Magazine']]
y = df['Type']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale the features using StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Initialize and train the KNN classifier
knn = KNeighborsClassifier(n_neighbors=5) # You can adjust the number of neighbors
knn.fit(X_train, y_train)

# Make predictions
y_pred = knn.predict(X_test)

# Evaluate the model
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[11  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  6  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 17  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  3  0  0  0]
 [ 0  0  0  0 16  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 23  0  0  0  0  0  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  8  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  3  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0 19  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 13  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 13  0  1  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0  0 11  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 10  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  1  0 12  0  0  0]
 [ 1  0  0  0  0  0  0  0  0  0  0  0  0  0 13  0  0]
 [ 0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  6  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  5]]
                     precision    recall  f1-score   support

         Auto Rifle

<ipython-input-5-d6656a5de0e3>:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[column].fillna(df[column].mean(), inplace=True)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: Und

In [6]:
from sklearn.tree import DecisionTreeClassifier

# Initialize and train the Decision Tree classifier
dtree = DecisionTreeClassifier()
dtree.fit(X_train, y_train)

# Make predictions
y_pred_dtree = dtree.predict(X_test)

# Evaluate the model
print(confusion_matrix(y_test, y_pred_dtree))
print(classification_report(y_test, y_pred_dtree))

[[11  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  6  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 17  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  3  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 16  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 24  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  8  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  3  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0 19  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 13  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 13  0  1  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 13  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  9  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 13  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 14  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  7  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  5]]
                     precision    recall  f1-score   support

         Auto Rifle

In [7]:
from sklearn.ensemble import RandomForestClassifier

# Initialize and train the Random Forest classifier
rf = RandomForestClassifier(n_estimators=100, random_state=42) # You can adjust the number of estimators
rf.fit(X_train, y_train)

# Make predictions
y_pred_rf = rf.predict(X_test)

# Evaluate the model
print(confusion_matrix(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))

[[11  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  6  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 17  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  3  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 16  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 24  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  8  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  3  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 13  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 13  0  1  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0  0 12  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 10  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 13  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 14  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  7  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  5]]
                     precision    recall  f1-score   support

         Auto Rifle

In [8]:
from sklearn.svm import SVC

# Initialize and train the SVM classifier
svm = SVC(kernel='linear') # You can change the kernel (e.g., 'rbf', 'poly')
svm.fit(X_train, y_train)

# Make predictions
y_pred_svm = svm.predict(X_test)

# Evaluate the model
print(confusion_matrix(y_test, y_pred_svm))
print(classification_report(y_test, y_pred_svm))

[[11  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  6  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 17  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  3  0  0  0]
 [ 0  0  0  0 16  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 24  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  8  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  3  0  0  0  0  0  0  0  0  0]
 [ 4  0  0  0  0  0  0  0 16  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 13  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 12  0  2  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0  0  9  0  3  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 10  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  1  0 12  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 14  0  0]
 [ 0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  6  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  5]]
                     precision    recall  f1-score   support

         Auto Rifle

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [9]:
from sklearn.cluster import KMeans
from sklearn.ensemble import IsolationForest


# Feature scaling for clustering and anomaly detection
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


# 1. K-Means Clustering
kmeans = KMeans(n_clusters=17, random_state=42) # Use 17 clusters, which is the number of weapon types
kmeans.fit(X_scaled)
df['cluster'] = kmeans.labels_

# Analyze clusters (example: print the mean values of features for each cluster)
#print(df.groupby('cluster').mean())


# 2. Isolation Forest for Anomaly Detection
isolation_forest = IsolationForest(contamination=0.05, random_state=42) # Adjust contamination as needed
isolation_forest.fit(X_scaled)

df['anomaly_score'] = isolation_forest.decision_function(X_scaled)
df['anomaly'] = isolation_forest.predict(X_scaled)

# Anomalies are labeled as -1, inliers as 1
print(df[df['anomaly'] == -1])

                         Name  Impact  Range          RPM  Magazine  Element  \
1              Ager's Scepter     6.0   69.0  1000.000000      97.0   Stasis   
12                  Coldheart     6.0   60.0  1000.000000      95.0      Arc   
18            Dead Man's Tale   100.0   60.0   120.000000      14.0  Kinetic   
24                   Divinity     6.0   67.0  1000.000000      94.0      Arc   
30               Eriana's Vow   100.0  100.0    90.000000       6.0    Solar   
35                 Forerunner    35.0  100.0   200.000000      15.0  Kinetic   
37             Grand Overture    53.0   85.0   100.000000      70.0      Arc   
42              Heir Apparent    39.0   60.0   900.000000     115.0    Solar   
47           Legend of Acrius    85.0  100.0    55.000000       4.0      Arc   
49             Lord of Wolves    68.0   20.0   640.000000       5.0    Solar   
58        One Thousand Voices   100.0  100.0   308.486228       4.0    Solar   
59               Osteo Striga    25.0   

In [10]:
# Group data by 'Type'
grouped = df.groupby('Type')

# Iterate through each group and detect anomalies
for name, group in grouped:
    print(f"\nAnomaly detection for weapon type: {name}")

    # Select features for anomaly detection (excluding 'Type' and other non-numerical columns)
    features = group[['Impact', 'Range', 'RPM', 'Magazine']]

    # Scale features for anomaly detection (important for Isolation Forest)
    scaler = StandardScaler()
    features_scaled = scaler.fit_transform(features)

    # Apply Isolation Forest
    isolation_forest = IsolationForest(contamination=0.05, random_state=42)  # Adjust contamination as needed
    isolation_forest.fit(features_scaled)

    group['anomaly_score'] = isolation_forest.decision_function(features_scaled)
    group['anomaly'] = isolation_forest.predict(features_scaled)

    # Print anomalies (-1 indicates an anomaly)
    print(group[group['anomaly'] == -1])


Anomaly detection for weapon type: Auto Rifle
                  Name  Impact  Range    RPM  Magazine  Element        Type  \
10          Cerberus+1    33.0    0.0  360.0      31.0  Kinetic  Auto Rifle   
69    S U R O S Regime    21.0   45.0  600.0      25.0  Kinetic  Auto Rifle   
75      Sweet Business    18.0   30.0  360.0      45.0  Kinetic  Auto Rifle   
95   Tommy's Matchbook    18.0   43.0  720.0      72.0    Solar  Auto Rifle   
977    Khvostov 7 G-02    21.0   12.0  600.0      40.0  Kinetic  Auto Rifle   

     Rarity  cluster  anomaly_score  anomaly  
10   Exotic       14      -0.123360       -1  
69   Exotic       16      -0.010751       -1  
75   Exotic        2      -0.102128       -1  
95   Exotic        4      -0.125698       -1  
977  Common        2      -0.021671       -1  

Anomaly detection for weapon type: Combat Bow
                  Name  Impact      Range         RPM   Magazine Element  \
48  Leviathan's Breath    60.0  44.183698  308.486228  20.211962    Void 

In [16]:
# Feature Importance for Random Forest
importances = rf.feature_importances_
feature_names = ['Impact', 'Range', 'RPM', 'Magazine']

for feature_name, importance in zip(feature_names, importances):
    print(f'{feature_name}: {importance}')

Impact: 0.2978948084015193
Range: 0.08484596054586808
RPM: 0.3265589409305422
Magazine: 0.2907002901220705


In [18]:
from sklearn.model_selection import KFold, cross_val_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score


# Advanced Cross-Validation (K-Fold)
kf = KFold(n_splits=5, shuffle=True, random_state=42)  # 5-fold cross-validation

rf = RandomForestClassifier(n_estimators=100, random_state=42)
cv_scores = cross_val_score(rf, X_train, y_train, cv=kf, scoring='accuracy') # or other relevant scoring metric

print("Cross-validation scores:", cv_scores)
print("Mean cross-validation score:", np.mean(cv_scores))
print("Standard deviation of cross-validation scores:", np.std(cv_scores))


# Repeat the training and evaluation process for different model complexities

n_estimators_values = [50, 100, 200, 500] # Example: varying the number of trees in the forest
results = []

for n_estimators in n_estimators_values:
  rf = RandomForestClassifier(n_estimators=n_estimators, random_state=42)
  cv_scores = cross_val_score(rf, X_train, y_train, cv=kf, scoring='accuracy')

  # Error analysis (you can replace with other metrics)
  train_error = []
  test_error = []
  for train_index, test_index in kf.split(X_train):
      X_train_fold, X_test_fold = X_train[train_index], X_train[test_index]
      y_train_fold, y_test_fold = y_train.iloc[train_index], y_train.iloc[test_index]

      rf.fit(X_train_fold, y_train_fold)
      y_pred_train = rf.predict(X_train_fold)
      y_pred_test = rf.predict(X_test_fold)

      train_error.append(1-accuracy_score(y_train_fold, y_pred_train))
      test_error.append(1-accuracy_score(y_test_fold, y_pred_test))


  results.append({
      'n_estimators': n_estimators,
      'cv_scores': cv_scores,
      'mean_cv_accuracy': np.mean(cv_scores),
      'std_cv_accuracy': np.std(cv_scores),
      'mean_train_error': np.mean(train_error),
      'mean_test_error': np.mean(test_error)
  })

# Analyze the results
for result in results:
    print(f"n_estimators: {result['n_estimators']}")
    print(f"  Mean CV Accuracy: {result['mean_cv_accuracy']}")
    print(f"  Std CV Accuracy: {result['std_cv_accuracy']}")
    print(f"  Mean Train Error: {result['mean_train_error']}")
    print(f"  Mean Test Error: {result['mean_test_error']}")


Cross-validation scores: [0.96202532 0.94936709 0.98101266 0.95541401 0.98089172]
Mean cross-validation score: 0.9657421591550431
Standard deviation of cross-validation scores: 0.013048569204996481
n_estimators: 50
  Mean CV Accuracy: 0.9632105135854229
  Std CV Accuracy: 0.016697719157586353
  Mean Train Error: 0.0
  Mean Test Error: 0.03678948641457711
n_estimators: 100
  Mean CV Accuracy: 0.9657421591550431
  Std CV Accuracy: 0.013048569204996481
  Mean Train Error: 0.0
  Mean Test Error: 0.034257840844956866
n_estimators: 200
  Mean CV Accuracy: 0.964476336370233
  Std CV Accuracy: 0.014769233642658178
  Mean Train Error: 0.0
  Mean Test Error: 0.03552366362976698
n_estimators: 500
  Mean CV Accuracy: 0.9657421591550431
  Std CV Accuracy: 0.014776142188471115
  Mean Train Error: 0.0
  Mean Test Error: 0.034257840844956845
